version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hamilton-js-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p29xaazzub4t"
s3_prefix = "hamilton-js-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
